// Generated by CoffeeScript 1.6.3
(function() {
  var Renderer, marked;

  Renderer = require("../lib/renderer");

  marked = require("marked");

  describe("Renderer", function() {
    var render;
    render = function(inputText) {
      return marked(inputText, {
        renderer: new Renderer()
      });
    };
    return it("renders strong text to bold face", function(done) {
      render("**text**").should.eql("\\textbf{text}");
      render("__text__").should.eql("\\textbf{text}");
      return done();
    });
  });

}).call(this);
