// Generated by CoffeeScript 1.6.3
(function() {
  var Renderer;

  module.exports = Renderer = (function() {
    function Renderer() {}

    Renderer.prototype.strong = function(text) {
      return "\\textbf{" + text + "}";
    };

    Renderer.prototype.paragraph = function(text) {
      return "" + text + "\n\n";
    };

    return Renderer;

  })();

}).call(this);
