// Generated by CoffeeScript 1.6.3
(function() {
  var Renderer;

  module.exports = Renderer = (function() {
    function Renderer() {}

    Renderer.prototype.em = function(text) {
      return "\\textit{" + text + "}";
    };

    Renderer.prototype.strong = function(text) {
      return "\\textbf{" + text + "}";
    };

    Renderer.prototype.codespan = function(text) {
      return "\\texttt{" + text + "}";
    };

    Renderer.prototype.br = function(text) {
      return "" + text + "\n";
    };

    Renderer.prototype.del = function(text) {
      return text;
    };

    Renderer.prototype.link = function(href, title, text) {
      return "\\url{" + href + "}";
    };

    Renderer.prototype.image = function(href, title, text) {
      return "";
    };

    Renderer.prototype.paragraph = function(text) {
      return "" + text + "\n\n";
    };

    return Renderer;

  })();

}).call(this);
